//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace XboxGamepassMVC.API_Clientes {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="API_XboxGamepassSoap", Namespace="http://tempuri.org/")]
    public partial class API_XboxGamepass : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback InsertarOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActualizarOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarPorIdOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public API_XboxGamepass() {
            this.Url = global::XboxGamepassMVC.Properties.Settings.Default.XboxGamepassMVC_API_Clientes_API_XboxGamepass;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event InsertarCompletedEventHandler InsertarCompleted;
        
        /// <remarks/>
        public event ActualizarCompletedEventHandler ActualizarCompleted;
        
        /// <remarks/>
        public event EliminarCompletedEventHandler EliminarCompleted;
        
        /// <remarks/>
        public event ListarCompletedEventHandler ListarCompleted;
        
        /// <remarks/>
        public event buscarPorIdCompletedEventHandler buscarPorIdCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Insertar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Insertar(Cliente cliente) {
            this.Invoke("Insertar", new object[] {
                        cliente});
        }
        
        /// <remarks/>
        public void InsertarAsync(Cliente cliente) {
            this.InsertarAsync(cliente, null);
        }
        
        /// <remarks/>
        public void InsertarAsync(Cliente cliente, object userState) {
            if ((this.InsertarOperationCompleted == null)) {
                this.InsertarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertarOperationCompleted);
            }
            this.InvokeAsync("Insertar", new object[] {
                        cliente}, this.InsertarOperationCompleted, userState);
        }
        
        private void OnInsertarOperationCompleted(object arg) {
            if ((this.InsertarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertarCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Actualizar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Actualizar(Cliente cliente) {
            this.Invoke("Actualizar", new object[] {
                        cliente});
        }
        
        /// <remarks/>
        public void ActualizarAsync(Cliente cliente) {
            this.ActualizarAsync(cliente, null);
        }
        
        /// <remarks/>
        public void ActualizarAsync(Cliente cliente, object userState) {
            if ((this.ActualizarOperationCompleted == null)) {
                this.ActualizarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizarOperationCompleted);
            }
            this.InvokeAsync("Actualizar", new object[] {
                        cliente}, this.ActualizarOperationCompleted, userState);
        }
        
        private void OnActualizarOperationCompleted(object arg) {
            if ((this.ActualizarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizarCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Eliminar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Eliminar(string cedula) {
            this.Invoke("Eliminar", new object[] {
                        cedula});
        }
        
        /// <remarks/>
        public void EliminarAsync(string cedula) {
            this.EliminarAsync(cedula, null);
        }
        
        /// <remarks/>
        public void EliminarAsync(string cedula, object userState) {
            if ((this.EliminarOperationCompleted == null)) {
                this.EliminarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarOperationCompleted);
            }
            this.InvokeAsync("Eliminar", new object[] {
                        cedula}, this.EliminarOperationCompleted, userState);
        }
        
        private void OnEliminarOperationCompleted(object arg) {
            if ((this.EliminarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Listar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Cliente[] Listar() {
            object[] results = this.Invoke("Listar", new object[0]);
            return ((Cliente[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarAsync() {
            this.ListarAsync(null);
        }
        
        /// <remarks/>
        public void ListarAsync(object userState) {
            if ((this.ListarOperationCompleted == null)) {
                this.ListarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarOperationCompleted);
            }
            this.InvokeAsync("Listar", new object[0], this.ListarOperationCompleted, userState);
        }
        
        private void OnListarOperationCompleted(object arg) {
            if ((this.ListarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarCompleted(this, new ListarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarPorId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Cliente buscarPorId(string id) {
            object[] results = this.Invoke("buscarPorId", new object[] {
                        id});
            return ((Cliente)(results[0]));
        }
        
        /// <remarks/>
        public void buscarPorIdAsync(string id) {
            this.buscarPorIdAsync(id, null);
        }
        
        /// <remarks/>
        public void buscarPorIdAsync(string id, object userState) {
            if ((this.buscarPorIdOperationCompleted == null)) {
                this.buscarPorIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarPorIdOperationCompleted);
            }
            this.InvokeAsync("buscarPorId", new object[] {
                        id}, this.buscarPorIdOperationCompleted, userState);
        }
        
        private void OnbuscarPorIdOperationCompleted(object arg) {
            if ((this.buscarPorIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarPorIdCompleted(this, new buscarPorIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Cliente {
        
        private string cli_CedulaField;
        
        private string cli_NombreField;
        
        private string cli_ApellidoField;
        
        private System.Nullable<System.DateTime> cli_BirthDateField;
        
        private string cli_PaisField;
        
        private string cli_EmailField;
        
        private System.Nullable<bool> cli_LogicalDeleteField;
        
        private Pago[] pagosField;
        
        /// <remarks/>
        public string Cli_Cedula {
            get {
                return this.cli_CedulaField;
            }
            set {
                this.cli_CedulaField = value;
            }
        }
        
        /// <remarks/>
        public string Cli_Nombre {
            get {
                return this.cli_NombreField;
            }
            set {
                this.cli_NombreField = value;
            }
        }
        
        /// <remarks/>
        public string Cli_Apellido {
            get {
                return this.cli_ApellidoField;
            }
            set {
                this.cli_ApellidoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Cli_BirthDate {
            get {
                return this.cli_BirthDateField;
            }
            set {
                this.cli_BirthDateField = value;
            }
        }
        
        /// <remarks/>
        public string Cli_Pais {
            get {
                return this.cli_PaisField;
            }
            set {
                this.cli_PaisField = value;
            }
        }
        
        /// <remarks/>
        public string Cli_Email {
            get {
                return this.cli_EmailField;
            }
            set {
                this.cli_EmailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> Cli_LogicalDelete {
            get {
                return this.cli_LogicalDeleteField;
            }
            set {
                this.cli_LogicalDeleteField = value;
            }
        }
        
        /// <remarks/>
        public Pago[] Pagos {
            get {
                return this.pagosField;
            }
            set {
                this.pagosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Pago {
        
        private int pago_IDField;
        
        private string pago_CodigoField;
        
        private string cli_CedulaField;
        
        private string sus_IDField;
        
        private System.Nullable<decimal> pago_MontoField;
        
        private System.Nullable<System.DateTime> pago_FechaField;
        
        private string pago_EstadoField;
        
        private System.Nullable<bool> pago_LogicalDeleteField;
        
        private Cliente clienteField;
        
        private Suscripcion suscripcionField;
        
        /// <remarks/>
        public int Pago_ID {
            get {
                return this.pago_IDField;
            }
            set {
                this.pago_IDField = value;
            }
        }
        
        /// <remarks/>
        public string Pago_Codigo {
            get {
                return this.pago_CodigoField;
            }
            set {
                this.pago_CodigoField = value;
            }
        }
        
        /// <remarks/>
        public string Cli_Cedula {
            get {
                return this.cli_CedulaField;
            }
            set {
                this.cli_CedulaField = value;
            }
        }
        
        /// <remarks/>
        public string Sus_ID {
            get {
                return this.sus_IDField;
            }
            set {
                this.sus_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> Pago_Monto {
            get {
                return this.pago_MontoField;
            }
            set {
                this.pago_MontoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Pago_Fecha {
            get {
                return this.pago_FechaField;
            }
            set {
                this.pago_FechaField = value;
            }
        }
        
        /// <remarks/>
        public string Pago_Estado {
            get {
                return this.pago_EstadoField;
            }
            set {
                this.pago_EstadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> Pago_LogicalDelete {
            get {
                return this.pago_LogicalDeleteField;
            }
            set {
                this.pago_LogicalDeleteField = value;
            }
        }
        
        /// <remarks/>
        public Cliente Cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
            }
        }
        
        /// <remarks/>
        public Suscripcion Suscripcion {
            get {
                return this.suscripcionField;
            }
            set {
                this.suscripcionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Suscripcion {
        
        private string sus_IDField;
        
        private int plan_IDField;
        
        private System.Nullable<System.DateTime> sus_StartDateField;
        
        private System.Nullable<System.DateTime> sus_EndDateField;
        
        private string sus_EstadoField;
        
        private System.Nullable<bool> sus_RenovacionAutoField;
        
        private System.Nullable<bool> sus_LogicalDeleteField;
        
        private Pago[] pagosField;
        
        private Plan planField;
        
        /// <remarks/>
        public string Sus_ID {
            get {
                return this.sus_IDField;
            }
            set {
                this.sus_IDField = value;
            }
        }
        
        /// <remarks/>
        public int Plan_ID {
            get {
                return this.plan_IDField;
            }
            set {
                this.plan_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Sus_StartDate {
            get {
                return this.sus_StartDateField;
            }
            set {
                this.sus_StartDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Sus_EndDate {
            get {
                return this.sus_EndDateField;
            }
            set {
                this.sus_EndDateField = value;
            }
        }
        
        /// <remarks/>
        public string Sus_Estado {
            get {
                return this.sus_EstadoField;
            }
            set {
                this.sus_EstadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> Sus_RenovacionAuto {
            get {
                return this.sus_RenovacionAutoField;
            }
            set {
                this.sus_RenovacionAutoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> Sus_LogicalDelete {
            get {
                return this.sus_LogicalDeleteField;
            }
            set {
                this.sus_LogicalDeleteField = value;
            }
        }
        
        /// <remarks/>
        public Pago[] Pagos {
            get {
                return this.pagosField;
            }
            set {
                this.pagosField = value;
            }
        }
        
        /// <remarks/>
        public Plan Plan {
            get {
                return this.planField;
            }
            set {
                this.planField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Plan {
        
        private int plan_IDField;
        
        private string plan_NombreField;
        
        private string plan_DuracionField;
        
        private System.Nullable<decimal> plan_PrecioField;
        
        private string plan_PlataformaField;
        
        private System.Nullable<bool> plan_LogicalDeleteField;
        
        private Suscripcion[] suscripcionsField;
        
        /// <remarks/>
        public int Plan_ID {
            get {
                return this.plan_IDField;
            }
            set {
                this.plan_IDField = value;
            }
        }
        
        /// <remarks/>
        public string Plan_Nombre {
            get {
                return this.plan_NombreField;
            }
            set {
                this.plan_NombreField = value;
            }
        }
        
        /// <remarks/>
        public string Plan_Duracion {
            get {
                return this.plan_DuracionField;
            }
            set {
                this.plan_DuracionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> Plan_Precio {
            get {
                return this.plan_PrecioField;
            }
            set {
                this.plan_PrecioField = value;
            }
        }
        
        /// <remarks/>
        public string Plan_Plataforma {
            get {
                return this.plan_PlataformaField;
            }
            set {
                this.plan_PlataformaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> Plan_LogicalDelete {
            get {
                return this.plan_LogicalDeleteField;
            }
            set {
                this.plan_LogicalDeleteField = value;
            }
        }
        
        /// <remarks/>
        public Suscripcion[] Suscripcions {
            get {
                return this.suscripcionsField;
            }
            set {
                this.suscripcionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void InsertarCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ActualizarCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void EliminarCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ListarCompletedEventHandler(object sender, ListarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cliente[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cliente[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void buscarPorIdCompletedEventHandler(object sender, buscarPorIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarPorIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarPorIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cliente Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cliente)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591