//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace XboxGamepassMVC.API_StoredProcedures {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="API_StoredProceduresXboxSoap", Namespace="http://tempuri.org/")]
    public partial class API_StoredProceduresXbox : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ListarClientesConSuscripcionActivaInactivaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarClientesConRenovacionAutomaticaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarClientesPorPaisYPlanOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarClientesPorPlataformaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarNumeroClientesPorPaisOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarPorIdOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public API_StoredProceduresXbox() {
            this.Url = global::XboxGamepassMVC.Properties.Settings.Default.XboxGamepassMVC_API_StoredProcedures_API_StoredProceduresXbox;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ListarClientesConSuscripcionActivaInactivaCompletedEventHandler ListarClientesConSuscripcionActivaInactivaCompleted;
        
        /// <remarks/>
        public event ListarClientesConRenovacionAutomaticaCompletedEventHandler ListarClientesConRenovacionAutomaticaCompleted;
        
        /// <remarks/>
        public event ListarClientesPorPaisYPlanCompletedEventHandler ListarClientesPorPaisYPlanCompleted;
        
        /// <remarks/>
        public event ListarClientesPorPlataformaCompletedEventHandler ListarClientesPorPlataformaCompleted;
        
        /// <remarks/>
        public event ListarNumeroClientesPorPaisCompletedEventHandler ListarNumeroClientesPorPaisCompleted;
        
        /// <remarks/>
        public event buscarPorIdCompletedEventHandler buscarPorIdCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarClientesConSuscripcionActivaInactiva", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SPClientesConSuscripcionActivaInactiva_Result[] ListarClientesConSuscripcionActivaInactiva() {
            object[] results = this.Invoke("ListarClientesConSuscripcionActivaInactiva", new object[0]);
            return ((SPClientesConSuscripcionActivaInactiva_Result[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarClientesConSuscripcionActivaInactivaAsync() {
            this.ListarClientesConSuscripcionActivaInactivaAsync(null);
        }
        
        /// <remarks/>
        public void ListarClientesConSuscripcionActivaInactivaAsync(object userState) {
            if ((this.ListarClientesConSuscripcionActivaInactivaOperationCompleted == null)) {
                this.ListarClientesConSuscripcionActivaInactivaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarClientesConSuscripcionActivaInactivaOperationCompleted);
            }
            this.InvokeAsync("ListarClientesConSuscripcionActivaInactiva", new object[0], this.ListarClientesConSuscripcionActivaInactivaOperationCompleted, userState);
        }
        
        private void OnListarClientesConSuscripcionActivaInactivaOperationCompleted(object arg) {
            if ((this.ListarClientesConSuscripcionActivaInactivaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarClientesConSuscripcionActivaInactivaCompleted(this, new ListarClientesConSuscripcionActivaInactivaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarClientesConRenovacionAutomatica", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SPObtenerClientesConRenovacionAutomatica_Result[] ListarClientesConRenovacionAutomatica() {
            object[] results = this.Invoke("ListarClientesConRenovacionAutomatica", new object[0]);
            return ((SPObtenerClientesConRenovacionAutomatica_Result[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarClientesConRenovacionAutomaticaAsync() {
            this.ListarClientesConRenovacionAutomaticaAsync(null);
        }
        
        /// <remarks/>
        public void ListarClientesConRenovacionAutomaticaAsync(object userState) {
            if ((this.ListarClientesConRenovacionAutomaticaOperationCompleted == null)) {
                this.ListarClientesConRenovacionAutomaticaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarClientesConRenovacionAutomaticaOperationCompleted);
            }
            this.InvokeAsync("ListarClientesConRenovacionAutomatica", new object[0], this.ListarClientesConRenovacionAutomaticaOperationCompleted, userState);
        }
        
        private void OnListarClientesConRenovacionAutomaticaOperationCompleted(object arg) {
            if ((this.ListarClientesConRenovacionAutomaticaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarClientesConRenovacionAutomaticaCompleted(this, new ListarClientesConRenovacionAutomaticaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarClientesPorPaisYPlan", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SPObtenerClientesPorPaisYPlan_Result[] ListarClientesPorPaisYPlan() {
            object[] results = this.Invoke("ListarClientesPorPaisYPlan", new object[0]);
            return ((SPObtenerClientesPorPaisYPlan_Result[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarClientesPorPaisYPlanAsync() {
            this.ListarClientesPorPaisYPlanAsync(null);
        }
        
        /// <remarks/>
        public void ListarClientesPorPaisYPlanAsync(object userState) {
            if ((this.ListarClientesPorPaisYPlanOperationCompleted == null)) {
                this.ListarClientesPorPaisYPlanOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarClientesPorPaisYPlanOperationCompleted);
            }
            this.InvokeAsync("ListarClientesPorPaisYPlan", new object[0], this.ListarClientesPorPaisYPlanOperationCompleted, userState);
        }
        
        private void OnListarClientesPorPaisYPlanOperationCompleted(object arg) {
            if ((this.ListarClientesPorPaisYPlanCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarClientesPorPaisYPlanCompleted(this, new ListarClientesPorPaisYPlanCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarClientesPorPlataforma", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SPObtenerClientesPorPlataforma_Result[] ListarClientesPorPlataforma() {
            object[] results = this.Invoke("ListarClientesPorPlataforma", new object[0]);
            return ((SPObtenerClientesPorPlataforma_Result[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarClientesPorPlataformaAsync() {
            this.ListarClientesPorPlataformaAsync(null);
        }
        
        /// <remarks/>
        public void ListarClientesPorPlataformaAsync(object userState) {
            if ((this.ListarClientesPorPlataformaOperationCompleted == null)) {
                this.ListarClientesPorPlataformaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarClientesPorPlataformaOperationCompleted);
            }
            this.InvokeAsync("ListarClientesPorPlataforma", new object[0], this.ListarClientesPorPlataformaOperationCompleted, userState);
        }
        
        private void OnListarClientesPorPlataformaOperationCompleted(object arg) {
            if ((this.ListarClientesPorPlataformaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarClientesPorPlataformaCompleted(this, new ListarClientesPorPlataformaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarNumeroClientesPorPais", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SPObtenerNumeroClientesPorPais_Result[] ListarNumeroClientesPorPais() {
            object[] results = this.Invoke("ListarNumeroClientesPorPais", new object[0]);
            return ((SPObtenerNumeroClientesPorPais_Result[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarNumeroClientesPorPaisAsync() {
            this.ListarNumeroClientesPorPaisAsync(null);
        }
        
        /// <remarks/>
        public void ListarNumeroClientesPorPaisAsync(object userState) {
            if ((this.ListarNumeroClientesPorPaisOperationCompleted == null)) {
                this.ListarNumeroClientesPorPaisOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarNumeroClientesPorPaisOperationCompleted);
            }
            this.InvokeAsync("ListarNumeroClientesPorPais", new object[0], this.ListarNumeroClientesPorPaisOperationCompleted, userState);
        }
        
        private void OnListarNumeroClientesPorPaisOperationCompleted(object arg) {
            if ((this.ListarNumeroClientesPorPaisCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarNumeroClientesPorPaisCompleted(this, new ListarNumeroClientesPorPaisCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarPorId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SPObtenerPagosPorPlan_Result buscarPorId(string nombrePlan) {
            object[] results = this.Invoke("buscarPorId", new object[] {
                        nombrePlan});
            return ((SPObtenerPagosPorPlan_Result)(results[0]));
        }
        
        /// <remarks/>
        public void buscarPorIdAsync(string nombrePlan) {
            this.buscarPorIdAsync(nombrePlan, null);
        }
        
        /// <remarks/>
        public void buscarPorIdAsync(string nombrePlan, object userState) {
            if ((this.buscarPorIdOperationCompleted == null)) {
                this.buscarPorIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarPorIdOperationCompleted);
            }
            this.InvokeAsync("buscarPorId", new object[] {
                        nombrePlan}, this.buscarPorIdOperationCompleted, userState);
        }
        
        private void OnbuscarPorIdOperationCompleted(object arg) {
            if ((this.buscarPorIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarPorIdCompleted(this, new buscarPorIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SPClientesConSuscripcionActivaInactiva_Result {
        
        private System.Nullable<int> clientesConSuscripcionActivaField;
        
        private System.Nullable<int> clientesSinSuscripcionActivaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ClientesConSuscripcionActiva {
            get {
                return this.clientesConSuscripcionActivaField;
            }
            set {
                this.clientesConSuscripcionActivaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ClientesSinSuscripcionActiva {
            get {
                return this.clientesSinSuscripcionActivaField;
            }
            set {
                this.clientesSinSuscripcionActivaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SPObtenerPagosPorPlan_Result {
        
        private string nombrePlanField;
        
        private System.Nullable<int> numeroPagosField;
        
        /// <remarks/>
        public string NombrePlan {
            get {
                return this.nombrePlanField;
            }
            set {
                this.nombrePlanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> NumeroPagos {
            get {
                return this.numeroPagosField;
            }
            set {
                this.numeroPagosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SPObtenerNumeroClientesPorPais_Result {
        
        private string paisField;
        
        private System.Nullable<int> numeroClientesField;
        
        /// <remarks/>
        public string Pais {
            get {
                return this.paisField;
            }
            set {
                this.paisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> NumeroClientes {
            get {
                return this.numeroClientesField;
            }
            set {
                this.numeroClientesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SPObtenerClientesPorPlataforma_Result {
        
        private string plataformaField;
        
        private System.Nullable<int> numeroClientesField;
        
        /// <remarks/>
        public string Plataforma {
            get {
                return this.plataformaField;
            }
            set {
                this.plataformaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> NumeroClientes {
            get {
                return this.numeroClientesField;
            }
            set {
                this.numeroClientesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SPObtenerClientesPorPaisYPlan_Result {
        
        private string paisField;
        
        private System.Nullable<int> numeroClientesField;
        
        private string nombrePlanField;
        
        private string duracionPlanField;
        
        /// <remarks/>
        public string Pais {
            get {
                return this.paisField;
            }
            set {
                this.paisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> NumeroClientes {
            get {
                return this.numeroClientesField;
            }
            set {
                this.numeroClientesField = value;
            }
        }
        
        /// <remarks/>
        public string NombrePlan {
            get {
                return this.nombrePlanField;
            }
            set {
                this.nombrePlanField = value;
            }
        }
        
        /// <remarks/>
        public string DuracionPlan {
            get {
                return this.duracionPlanField;
            }
            set {
                this.duracionPlanField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SPObtenerClientesConRenovacionAutomatica_Result {
        
        private System.Nullable<int> numeroClientesField;
        
        private System.Nullable<bool> renovacionAutomaticaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> NumeroClientes {
            get {
                return this.numeroClientesField;
            }
            set {
                this.numeroClientesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> RenovacionAutomatica {
            get {
                return this.renovacionAutomaticaField;
            }
            set {
                this.renovacionAutomaticaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ListarClientesConSuscripcionActivaInactivaCompletedEventHandler(object sender, ListarClientesConSuscripcionActivaInactivaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarClientesConSuscripcionActivaInactivaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarClientesConSuscripcionActivaInactivaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SPClientesConSuscripcionActivaInactiva_Result[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SPClientesConSuscripcionActivaInactiva_Result[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ListarClientesConRenovacionAutomaticaCompletedEventHandler(object sender, ListarClientesConRenovacionAutomaticaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarClientesConRenovacionAutomaticaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarClientesConRenovacionAutomaticaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SPObtenerClientesConRenovacionAutomatica_Result[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SPObtenerClientesConRenovacionAutomatica_Result[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ListarClientesPorPaisYPlanCompletedEventHandler(object sender, ListarClientesPorPaisYPlanCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarClientesPorPaisYPlanCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarClientesPorPaisYPlanCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SPObtenerClientesPorPaisYPlan_Result[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SPObtenerClientesPorPaisYPlan_Result[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ListarClientesPorPlataformaCompletedEventHandler(object sender, ListarClientesPorPlataformaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarClientesPorPlataformaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarClientesPorPlataformaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SPObtenerClientesPorPlataforma_Result[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SPObtenerClientesPorPlataforma_Result[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ListarNumeroClientesPorPaisCompletedEventHandler(object sender, ListarNumeroClientesPorPaisCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarNumeroClientesPorPaisCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarNumeroClientesPorPaisCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SPObtenerNumeroClientesPorPais_Result[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SPObtenerNumeroClientesPorPais_Result[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void buscarPorIdCompletedEventHandler(object sender, buscarPorIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarPorIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarPorIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SPObtenerPagosPorPlan_Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SPObtenerPagosPorPlan_Result)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591